// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetExecutableDir(): $CancellablePromise<string> {
    return $Call.ByID(3686386630);
}

export function GetProp(group: string, key: string): $CancellablePromise<[any, boolean]> {
    return $Call.ByID(892741962, group, key);
}

/**
 * ReadConfig reads the Smash Soda configuration file from the %appdata% directory
 */
export function ReadConfig(): $CancellablePromise<[{ [_: string]: any }, boolean]> {
    return $Call.ByID(684624663).then(($result: any) => {
        $result[0] = $$createType0($result[0]);
        return $result;
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
