// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Start rich presence thread
 */
export function StartActivity(players: number, game: string, link: string): $CancellablePromise<void> {
    return $Call.ByID(2480652200, players, game, link);
}

/**
 * Stop rich presence thread
 */
export function StopActivity(): $CancellablePromise<void> {
    return $Call.ByID(2311198090);
}
