// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetFonts returns a list of unique font family names and their file paths
 * installed on the system.
 */
export function GetFonts(): $CancellablePromise<$models.FontInfo[]> {
    return $Call.ByID(3497718167).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ReadHTML reads an HTML file and returns its content as a string.
 */
export function ReadHTML(path: string): $CancellablePromise<string> {
    return $Call.ByID(3288513424, path);
}

/**
 * ReadImage reads an image file and returns it as a base64 encoded string.
 */
export function ReadImage(path: string): $CancellablePromise<string> {
    return $Call.ByID(1966375514, path);
}

/**
 * ReadText reads a text file and returns its content as a string.
 */
export function ReadText(path: string): $CancellablePromise<string> {
    return $Call.ByID(4022957342, path);
}

// Private type creation functions
const $$createType0 = $models.FontInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
