// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetWindowNames(): $CancellablePromise<string[]> {
    return $Call.ByID(1689828808).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StartWatchingFocus(windowName: string): $CancellablePromise<void> {
    return $Call.ByID(2185696527, windowName);
}

export function StopWatchingFocus(): $CancellablePromise<void> {
    return $Call.ByID(2446011467);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
