// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChangeHotkey(args: $models.ChangeHotkeyArgs): $CancellablePromise<void> {
    return $Call.ByID(3878511279, args);
}

export function RegisterHotkey(args: $models.RegisterHotkeyArgs): $CancellablePromise<void> {
    return $Call.ByID(13000566, args);
}

export function UnregisterAll(): $CancellablePromise<void> {
    return $Call.ByID(2533720786);
}
