// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChangeHotkeyArgs {
    "Name": string;
    "Modifiers": number[];
    "Key": number;

    /** Creates a new ChangeHotkeyArgs instance. */
    constructor($$source: Partial<ChangeHotkeyArgs> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Modifiers" in $$source)) {
            this["Modifiers"] = [];
        }
        if (!("Key" in $$source)) {
            this["Key"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangeHotkeyArgs instance from a string or object.
     */
    static createFrom($$source: any = {}): ChangeHotkeyArgs {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Modifiers" in $$parsedSource) {
            $$parsedSource["Modifiers"] = $$createField1_0($$parsedSource["Modifiers"]);
        }
        return new ChangeHotkeyArgs($$parsedSource as Partial<ChangeHotkeyArgs>);
    }
}

/**
 * FontInfo holds information about a system font.
 */
export class FontInfo {
    "name": string;
    "path": string;

    /** Creates a new FontInfo instance. */
    constructor($$source: Partial<FontInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FontInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FontInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FontInfo($$parsedSource as Partial<FontInfo>);
    }
}

/**
 * Monitor represents a display monitor with its properties.
 */
export class Monitor {
    /**
     * Display name (e.g., "[1] 1920x1080")
     */
    "Name": string;

    /**
     * Width of the monitor
     */
    "Width": number;

    /**
     * Height of the monitor
     */
    "Height": number;

    /**
     * X-coordinate of the monitor's position
     */
    "X": number;

    /**
     * Y-coordinate of the monitor's position
     */
    "Y": number;

    /**
     * Base64-encoded image preview of the monitor
     */
    "Preview": string;

    /** Creates a new Monitor instance. */
    constructor($$source: Partial<Monitor> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }
        if (!("X" in $$source)) {
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            this["Y"] = 0;
        }
        if (!("Preview" in $$source)) {
            this["Preview"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Monitor instance from a string or object.
     */
    static createFrom($$source: any = {}): Monitor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Monitor($$parsedSource as Partial<Monitor>);
    }
}

export class Plugin {
    "Meta": { [_: string]: any };
    "Name": string;
    "Path": string;
    "HTML": string;
    "JS": string;
    "CSS": string;
    "Config": { [_: string]: any };

    /** Creates a new Plugin instance. */
    constructor($$source: Partial<Plugin> = {}) {
        if (!("Meta" in $$source)) {
            this["Meta"] = {};
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("HTML" in $$source)) {
            this["HTML"] = "";
        }
        if (!("JS" in $$source)) {
            this["JS"] = "";
        }
        if (!("CSS" in $$source)) {
            this["CSS"] = "";
        }
        if (!("Config" in $$source)) {
            this["Config"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plugin instance from a string or object.
     */
    static createFrom($$source: any = {}): Plugin {
        const $$createField0_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Meta" in $$parsedSource) {
            $$parsedSource["Meta"] = $$createField0_0($$parsedSource["Meta"]);
        }
        if ("Config" in $$parsedSource) {
            $$parsedSource["Config"] = $$createField6_0($$parsedSource["Config"]);
        }
        return new Plugin($$parsedSource as Partial<Plugin>);
    }
}

export class RegisterHotkeyArgs {
    "Name": string;
    "Modifiers": number[];
    "Key": number;
    "Event": string;

    /** Creates a new RegisterHotkeyArgs instance. */
    constructor($$source: Partial<RegisterHotkeyArgs> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Modifiers" in $$source)) {
            this["Modifiers"] = [];
        }
        if (!("Key" in $$source)) {
            this["Key"] = 0;
        }
        if (!("Event" in $$source)) {
            this["Event"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegisterHotkeyArgs instance from a string or object.
     */
    static createFrom($$source: any = {}): RegisterHotkeyArgs {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Modifiers" in $$parsedSource) {
            $$parsedSource["Modifiers"] = $$createField1_0($$parsedSource["Modifiers"]);
        }
        return new RegisterHotkeyArgs($$parsedSource as Partial<RegisterHotkeyArgs>);
    }
}

export class Theme {
    "ID": string;
    "Meta": { [_: string]: any };

    /** Creates a new Theme instance. */
    constructor($$source: Partial<Theme> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Meta" in $$source)) {
            this["Meta"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     */
    static createFrom($$source: any = {}): Theme {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Meta" in $$parsedSource) {
            $$parsedSource["Meta"] = $$createField1_0($$parsedSource["Meta"]);
        }
        return new Theme($$parsedSource as Partial<Theme>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
