// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeletePlugin(pluginId: string): $CancellablePromise<void> {
    return $Call.ByID(2468250636, pluginId);
}

/**
 * DownloadPlugin downloads a plugin's files from GitHub raw URL into plugins/<pluginID>/ folder
 */
export function DownloadPlugin(pluginID: string, files: string[]): $CancellablePromise<void> {
    return $Call.ByID(1815058439, pluginID, files);
}

/**
 * LoadPlugins loads all locally saved plugins into memory
 */
export function LoadPlugins(): $CancellablePromise<$models.Plugin[]> {
    return $Call.ByID(4074606848).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Plugin.createFrom;
const $$createType1 = $Create.Array($$createType0);
