// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DownloadTheme(themeID: string, files: string[]): $CancellablePromise<void> {
    return $Call.ByID(3000947091, themeID, files);
}

export function GetOverlayStyles(): $CancellablePromise<$models.Theme[]> {
    return $Call.ByID(2524536872).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetOverlayThemeCSS(themeID: string): $CancellablePromise<string> {
    return $Call.ByID(2983351522, themeID);
}

// Private type creation functions
const $$createType0 = $models.Theme.createFrom;
const $$createType1 = $Create.Array($$createType0);
