// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Blur the overlay window
 */
export function Blur(): $CancellablePromise<void> {
    return $Call.ByID(1657873802);
}

/**
 * CreateStudioWindow creates the headless overlay window
 */
export function CreateHeadlessWindow(): $CancellablePromise<void> {
    return $Call.ByID(2421432972);
}

/**
 * CreateStudioWindow creates a new window for the overlay customization
 */
export function CreateStudioWindow(): $CancellablePromise<void> {
    return $Call.ByID(1415030933);
}

/**
 * Focus the overlay window
 */
export function Focus(): $CancellablePromise<void> {
    return $Call.ByID(1060711185);
}

/**
 * GetMonitors retrieves the list of monitors connected to the system.
 */
export function GetMonitors(): $CancellablePromise<$models.Monitor[]> {
    return $Call.ByID(1109440906).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetResolution(): $CancellablePromise<[number, number]> {
    return $Call.ByID(2402845531);
}

/**
 * Just a backend way to log messages
 */
export function Log(message: string): $CancellablePromise<void> {
    return $Call.ByID(2262534463, message);
}

/**
 * Reset has default value of false
 */
export function MoveMainWindowToMonitor(index: number): $CancellablePromise<void> {
    return $Call.ByID(1985551148, index);
}

// Private type creation functions
const $$createType0 = $models.Monitor.createFrom;
const $$createType1 = $Create.Array($$createType0);
